# Generated by Django 6.0.7 on 2026-07-22 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('idclass', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('idprof', models.AutoField(primary_key=True, serialize=False)),
                ('nomprof', models.CharField(max_length=100)),
                ('prenomprof', models.CharField(max_length=100)),
                ('grad', models.CharField(choices=[('PT', 'Professeur Titulaire'), ('MC', 'Maître de Conférences'), ('AESR', "Assistant d'Enseignement Supérieur et de Recherche"), ('HDR', 'Docteur HDR'), ('DI', 'Docteur en Informatique'), ('DOC', 'Doctorant en Informatique')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('idsalle', models.AutoField(primary_key=True, serialize=False)),
                ('design', models.CharField(max_length=100)),
                ('occupation', models.CharField(choices=[('Libre', 'Libre'), ('Occupee', 'Occupée')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('idclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.classe')),
                ('idprof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.professeur')),
                ('idsalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.salle')),
            ],
        ),
    ]
