# Generated by Django 6.0.7 on 2026-07-22 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('idprof', models.AutoField(primary_key=True, serialize=False)),
                ('nomprof', models.CharField(max_length=100)),
                ('prenomprof', models.CharField(max_length=100)),
                ('grad', models.CharField(choices=[('PP', 'Prof python'), ('PM', 'Prof de Merisse '), ('PMT', 'Prof de Mathes'), ('PS', 'Prof de SDSI'), ('PJ', 'Prof en Java')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='idprof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emploi.prof'),
        ),
        migrations.DeleteModel(
            name='Professeur',
        ),
    ]
