# Generated by Django 6.0.7 on 2026-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi', '0002_prof_alter_emploidutemps_idprof_delete_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='duree_minutes',
            field=models.PositiveIntegerField(choices=[(60, '1h'), (90, '1h30'), (120, '2h'), (180, '3h'), (240, '4h')], default=90),
        ),
        migrations.AlterField(
            model_name='prof',
            name='grad',
            field=models.CharField(choices=[('PT', 'Professeur Titulaire'), ('MC', 'Maître de Conférences'), ('AESR', "Assistant d'Enseignement Supérieur et de Recherche"), ('HDR', 'Docteur HDR'), ('DI', 'Docteur en Informatique'), ('DOC', 'Doctorant en Informatique')], max_length=10),
        ),
    ]
